name: Continuous Integration Testing

on: 
  pull_request:
    branches:
      - develop

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        test:
          [
            graphql-sample,
            mongo-sample,
          ]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: npm test
        run: npm run test:e2e

  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start Docker-Compose
        run: docker-compose up -d
      - name: npm install
        run: npm ci
      - name: Run tests
        run: npm run test:e2e
      - name: Collect coverage
        run: npm run test:cov:total
      - name: Stop Docker-Compose
        run: docker-compose down